/**
 * Persona: Bâtitec SA
 * PME de services techniques (construction / maintenance). ~8 employés.
 * Assujettie TVA. Volume élevé, clients variés, multi-devises.
 * Transitoires activés (décembre → janvier). 24 mois de données.
 */
import { MONTH_NAMES_FR } from '../helpers.js'

export const config = {
  monthsBack: 24,
  taxes: true,
  transitoires: true,

  company: {
    company_name: 'Bâtitec SA',
    address: 'Zone Industrielle 4, 1762 Givisiez',
    phone: '+41 26 466 12 34',
    email: 'administration@batitec.ch',
    bank_account: 'CH44 3000 4230 0000 0000 0',
    tva_enabled: true,
    tva_rate: 8.1,
    tva_number: 'CHE-123.456.789 TVA',
    payment_terms: 45,
    currency: 'CHF',
    ledger_categories: [
      'Revenu',
      'Frais',
      'Salaire',
      'AVS',
      'LPP',
      'LAA',
      'Assurance',
      'TVA',
      'Fiduciaire',
      'Mastercard',
      'Taxe',
      'Fonds propres',
      'Impôt',
    ].map(name => ({ name, patterns: [] })),
  },

  clients: [
    // Retainer / récurrents
    {
      name: 'Ville de Fribourg',
      address: 'Grand-Rue 111, 1700 Fribourg',
      email: 'technique@ville-fribourg.ch',
      phone: '+41 26 351 71 11',
      payment_terms: 60,
      retainer: { description: 'Contrat de maintenance bâtiments communaux', amount: 4800 },
    },
    {
      name: 'Immofri SA',
      address: 'Rue Saint-Pierre 12, 1700 Fribourg',
      email: 'gestion@immofri.ch',
      phone: '+41 26 321 00 44',
      payment_terms: 30,
      retainer: { description: 'Maintenance mensuelle parc locatif', amount: 2200 },
    },
    // Ad-hoc CHF
    {
      name: 'Commune de Bulle',
      address: 'Route de Riaz 1, 1630 Bulle',
      email: 'travaux@bulle.ch',
      phone: '+41 26 919 10 10',
      payment_terms: 60,
    },
    {
      name: 'Commune de Romont',
      address: "Rue de l'Hôtel-de-Ville 1, 1680 Romont",
      email: 'administration@romont.ch',
      phone: '+41 26 651 91 91',
      payment_terms: 60,
    },
    {
      name: 'Résidence Les Acacias',
      address: 'Chemin des Acacias 3, 1700 Fribourg',
      email: 'syndic@acacias-frib.ch',
      phone: '+41 26 466 55 22',
      payment_terms: 30,
    },
    {
      name: 'Centre commercial Fribourg-Centre',
      address: 'Route du Centre 18, 1752 Villars-sur-Glâne',
      email: 'facility@fribourg-centre.ch',
      phone: '+41 26 460 33 11',
      payment_terms: 45,
    },
    {
      name: 'Grand Hôtel Fribourg',
      address: 'Rue de Lausanne 14, 1700 Fribourg',
      email: 'maintenance@grandhotel-fribourg.ch',
      phone: '+41 26 351 10 10',
      payment_terms: 30,
    },
    {
      name: 'Jean-Marc Bourquin',
      address: 'Chemin des Pins 7, 1722 Bourguillon',
      email: 'jm.bourquin@gmail.com',
      phone: '+41 79 456 12 34',
      payment_terms: 15,
    },
    {
      name: 'Marie & Pierre Dupont',
      address: 'Route de Tavel 23, 1700 Fribourg',
      email: 'pierre.dupont@bluewin.ch',
      phone: '+41 79 234 56 78',
      payment_terms: 15,
    },
    {
      name: 'Régie Moléson Sàrl',
      address: 'Rue du Bourg 5, 1663 Gruyères',
      email: 'info@regie-moleson.ch',
      phone: '+41 26 921 22 33',
      payment_terms: 30,
    },
    {
      name: 'EcoFrib SA',
      address: 'Route de Villars 88, 1700 Fribourg',
      email: 'infrastructure@ecofrib.ch',
      phone: '+41 26 456 78 90',
      payment_terms: 30,
    },
    // Clients EUR
    {
      name: 'Schmid & Partner AG',
      address: 'Industriestrasse 12, 3175 Flamatt',
      email: 'rechnungen@schmid-partner.ch',
      phone: '+41 31 741 88 00',
      payment_terms: 30,
      currency: 'EUR',
    },
    {
      name: 'Immo-Alpine Holding GmbH',
      address: 'Bahnhofstrasse 3, 3011 Bern',
      email: 'immo@alpine-holding.ch',
      phone: '+41 31 320 44 55',
      payment_terms: 45,
      currency: 'EUR',
    },
    {
      name: 'Leroy Construction France SARL',
      address: '14 rue du Commerce, 01630 Saint-Genis-Pouilly',
      email: 'compta@leroy-construction.fr',
      phone: '+33 4 50 28 11 22',
      payment_terms: 45,
      currency: 'EUR',
    },
    // Client USD
    {
      name: 'TechBuild International Inc.',
      address: '350 Fifth Avenue, New York, NY 10118',
      email: 'ap@techbuild-intl.com',
      phone: '+1 212 555 0199',
      payment_terms: 30,
      currency: 'USD',
    },
  ],

  invoicesPerMonth: { min: 25, max: 40 },
  linesPerInvoice: { min: 2, max: 6 },

  lineTemplates: [
    { description: "Main d'œuvre — technicien", qMin: 4, qMax: 32, pMin: 85, pMax: 110 },
    { description: "Main d'œuvre — chef de chantier", qMin: 2, qMax: 16, pMin: 110, pMax: 140 },
    { description: 'Fournitures et matériaux', qMin: 1, qMax: 1, pMin: 200, pMax: 4500 },
    { description: 'Location équipement', qMin: 1, qMax: 3, pMin: 350, pMax: 1200 },
    { description: 'Travaux de finition', qMin: 1, qMax: 1, pMin: 500, pMax: 3000 },
    { description: 'Intervention urgence (forfait)', qMin: 1, qMax: 1, pMin: 350, pMax: 800 },
    { description: 'Frais de déplacement chantier', qMin: 1, qMax: 1, pMin: 80, pMax: 250 },
    { description: 'Sous-traitance spécialisée', qMin: 1, qMax: 1, pMin: 800, pMax: 5000 },
  ],
  lineWeights: [30, 15, 20, 8, 10, 7, 5, 5],

  charges: [
    // 8 salaires (4 + 4 regroupés par catégorie)
    {
      description: (y, m) => `Salaires ouvriers — ${MONTH_NAMES_FR[m]} ${y}`,
      category: 'Salaire',
      amountMin: 18500,
      amountMax: 20000,
      dayOfMonth: 25,
      every: 'month',
    },
    {
      description: (y, m) => `Salaires cadres — ${MONTH_NAMES_FR[m]} ${y}`,
      category: 'Salaire',
      amountMin: 14000,
      amountMax: 15500,
      dayOfMonth: 25,
      every: 'month',
    },
    {
      description: (y, m) => `Charges AVS/AI/APG patronales ${MONTH_NAMES_FR[m]} ${y}`,
      category: 'AVS',
      amountMin: 3300,
      amountMax: 3600,
      dayOfMonth: 28,
      every: 'month',
    },
    {
      description: (y, m) => `LPP part patronale ${MONTH_NAMES_FR[m]} ${y}`,
      category: 'LPP',
      amountMin: 2000,
      amountMax: 2300,
      dayOfMonth: 28,
      every: 'month',
    },
    {
      description: (y, m) => `LAA part patronale ${MONTH_NAMES_FR[m]} ${y}`,
      category: 'LAA',
      amountMin: 500,
      amountMax: 650,
      dayOfMonth: 28,
      every: 'month',
    },
    {
      description: 'Décompte TVA trimestriel',
      category: 'TVA',
      amountMin: 18000,
      amountMax: 26000,
      dayOfMonth: 20,
      every: 'quarter',
    },
    {
      description: 'Honoraires fiduciaire',
      category: 'Fiduciaire',
      amountMin: 3200,
      amountMax: 3800,
      dayOfMonth: 15,
      every: 'half-year',
    },
    {
      description: 'Frais Mastercard entreprise',
      category: 'Mastercard',
      amountMin: 1200,
      amountMax: 3000,
      dayOfMonth: 5,
      every: 'month',
    },
    {
      description: 'Assurance bâtiment et RC professionnelle',
      category: 'Assurance',
      amountMin: 2200,
      amountMax: 2600,
      dayOfMonth: 10,
      every: 'quarter',
    },
    {
      description: 'Frais généraux et fournitures bureau',
      category: 'Frais',
      amountMin: 300,
      amountMax: 1200,
      every: 'month',
      count: { min: 2, max: 4 },
    },
    {
      description: 'Taxe véhicules utilataires',
      category: 'Taxe',
      amountMin: 900,
      amountMax: 1200,
      dayOfMonth: 15,
      every: 'year',
      month: 3,
    },
  ],
}
